package model;

public class Player {
    private String name;
    private long health;
    private long strength;
    private long attack;


    /*
    * This constructor is used when game is created in custom mode.
    * Here user will provide name, health, strength, and attack values
    * */
    public Player(String name, long health, long strength, long attack) {
        if (health < 1 || strength < 1 || attack < 1) {
            throw new IllegalArgumentException("Invalid Input");
        }
        this.name = name;
        this.health = health;
        this.strength = strength;
        this.attack = attack;
    }


    /*
    * This constructor is used when game is created in default mode.
    * Here user will provide only player names other values will be generated by program
    * */
    public Player() {

    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public long getHealth() {
        return health;
    }

    public void setHealth(long health) {
        this.health = health;
    }

    public long getStrength() {
        return strength;
    }

    public void setStrength(long strength) {
        this.strength = strength;
    }

    public long getAttack() {
        return attack;
    }

    public void setAttack(long attack) {
        this.attack = attack;
    }
}
