package model;

public class Player {
    private String name;
    private long health;
    private long strength;
    private long attack;


    /*
    * This constructor is used when game is created in custom mode.
    * Here user will provide name, health, strength, and attack values
    * */
    public Player(String name, long health, long strength, long attack) {
        this.name = name;
        this.health = health;
        this.strength = strength;
        this.attack = attack;
    }


    /*
    * This constructor is used when game is created in default mode.
    * Here user will provide only player names other values will be generated by program
    * */
    public Player() {

    }


}
